<?php

/**
 * @var Magezil\Bestseller\Block\Product\Bestseller $block
 */

use Magento\Catalog\Block\Product\ReviewRendererInterface;
use Magento\Framework\App\Action\Action;
use Magento\Wishlist\Helper\Data as WishlistData;
use Magento\Catalog\Helper\Product\Compare;

$type = 'bestseller';
$image = 'category_page_list';
$templateType = ReviewRendererInterface::SHORT_VIEW;
$bestsellerConfig = $block->getBestsellerConfig();

if ($bestsellerConfig->hasBestsellerTitle()) {
    $title = $bestsellerConfig->getBestsellerTitle();
} else {
    $title = __('Bestseller Products:');
}

$items = $block->getLoadedProductCollection();
?>

<div class="block <?= $type ?>">

    <div class="block-title title">
        <strong id="block-<?= $type ?>-heading" role="heading" aria-level="2"><?= $block->escapeHtml($title) ?></strong>
    </div>

    <div class="block-actions">
        <?= $block->escapeHtml(__('Check items to add to the cart or')) ?>
        <button type="button" class="action select" id="select_all_bestseller" data-role="select-all-bestseller">
            <?= $block->escapeHtml(__('select all')) ?>
        </button>
        <form data-role="tocart-form" action="<?= $block->getUrl('bestseller/cart/addProductsSelectedInCart') ?>" method="post">
            <button type="submit" class="action to cart primary" id="add_all_bestseller"><?= __('All selected in cart') ?></button>
            <input id="bestseller_product_ids" name="productIds" hidden />
        </form>
    </div>

    <div class="block-content content block-content-bestseller" aria-labelledby="block-<?= $type ?>-heading">
        <div class="products wrapper grid products-grid products-<?= $type ?>">
            <ol class="products list items product-items">
                <?php foreach ($items as $_item) : ?>
                    <li class="card-list item product product-item">
                        <div class="product-item-info">
                            <?= '<!-- ' . $image . '-->' ?>
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product photo product-item-photo">
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>

                            <div class="product details product-item-details">
                                <strong class="product name product-item-name"><a class="product-item-link" title="<?= $block->escapeHtmlAttr($_item->getName()) ?>" href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>">
                                        <?= $block->escapeHtml($_item->getName()) ?></a>
                                </strong>

                                <!-- Product Price -->
                                <?= $block->getProductPrice($_item) ?>

                                <?php if ($templateType) : ?>
                                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                <?php if (!$_item->getRequiredOptions()) : ?>
                                    <div class="field choice bestseller">
                                        <input type="checkbox" class="checkbox-bestseller" id="bestseller-checkbox_<?= $block->escapeHtmlAttr($_item->getId()) ?>" name="bestseller[]" value="<?= $block->escapeHtmlAttr($_item->getId()) ?>" />
                                        <label class="label" for="bestseller-checkbox_<?= $block->escapeHtmlAttr($_item->getId()) ?>"><span><?= $block->escapeHtml(__('Add to Cart')) ?></span></label>
                                    </div>
                                <?php endif; ?>

                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions">
                                        <div class="actions-primary">
                                            <?php if ($_item->isSaleable()) : ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                    <?php if ($bestsellerConfig->isQtyButtonEnable()) : ?>
                                                        <div class="field qty">
                                                            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                                                            <div class="control">
                                                                <input type="number" name="qty" id="bestseller_qty_<?= $_item->getId() ?>" min="1" value="1" title="<?= $block->escapeHtmlAttr(__('Qty')) ?>" class="input-text qty" />
                                                            </div>
                                                        </div>
                                                    <?php endif; ?>
                                                    <input type="hidden" name="product" value="<?= $postParams['data']['product'] ?>">
                                                    <input type="hidden" name="<?= Action::PARAM_NAME_URL_ENCODED ?>" value="<?= $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <button type="submit" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>" class="action tocart primary add-to-cart">
                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                    </button>
                                                </form>
                                            <?php else : ?>
                                                <?php if ($_item->isAvailable()) : ?>
                                                    <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                <?php else : ?>
                                                    <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                    <div class="product-item-actions">
                                        <div data-role="add-to-links" class="actions-secondary" style="position: relative;">
                                            <!-- Add Product to Wishlist  -->
                                            <?php if ($this->helper(WishlistData::class)->isAllow()) : ?>
                                                <?php if ($bestsellerConfig->isWishlistButtonEnable()) : ?>
                                                    <a href="#" data-post='<?= $this->helper(WishlistData::class)->getAddParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                        <span><?= __('Add to Wish List') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            <?php endif; ?>

                                            <!-- Add Product to Comparison List -->
                                            <?php if ($bestsellerConfig->isCompareButtonEnable()) : ?>
                                                <?php $compareHelper = $this->helper(Compare::class); ?>
                                                <a href="#" class="action tocompare" title="<?= $block->escapeHtml(__('Add to Compare List')); ?>" aria-label="<?= $block->escapeHtml(__('Add to Compare List')); ?>" data-post='<?= $compareHelper->getPostDataParams($_item); ?>' role="button">
                                                    <span><?= __('Add to Compare List') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach ?>
            </ol>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*":
        {
            "Magezil_Bestseller/js/carouselBestseller": {},
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }
</script>